### ISSUE TITLE
Homebridge crashes after loading smtpsensor

### ISSUE THREAD

**Issue by neonightmare** [SphtKr/homebridge-smtpsensor#3]
Hi, big thx for this plugin, got this error

```
pi@raspberrypi ~/.homebridge $ homebridge 
*** WARNING *** The program 'node' uses the Apple Bonjour compatibility layer of Avahi.
*** WARNING *** Please fix your application to use the native API of Avahi!
*** WARNING *** For more information see <http://0pointer.de/avahi-compat?s=libdns_sd&e=node>
*** WARNING *** The program 'node' called 'DNSServiceRegister()' which is not supported (or only supported partially) in the Apple Bonjour compatibility layer of Avahi.
*** WARNING *** Please fix your application to use the native API of Avahi!
*** WARNING *** For more information see <http://0pointer.de/avahi-compat?s=libdns_sd&e=node&f=DNSServiceRegister>
Loaded plugin: homebridge-cmd
Registering accessory 'homebridge-cmd.CMD

---
Loaded plugin: homebridge-http
Registering accessory 'homebridge-http.Http

---
Loaded plugin: homebridge-httptemperaturehumidity
Registering accessory 'homebridge-httptemperaturehumidity.HttpTemphum

---
Loaded plugin: homebridge-knx
Registering platform 'homebridge-knx.KNX

---
*** WARNING *** The program node called DNSServiceRegister() which is not supported (or only supported partially) in the Apple Bonjour compatibility layer of Avahi.
*** WARNING *** Please fix your application to use the native API of Avahi!
*** WARNING *** For more information see <http://0pointer.de/avahi-compat?s=libdns_sd&e=node&f=DNSServiceRegister>
Loaded plugin: homebridge-mcuiot
Registering platform 'homebridge-mcuiot.mcuiot

---
Loaded plugin: homebridge-nukiio
Registering accessory 'homebridge-nukiio.Nuki

---
Loaded plugin: homebridge-samsungtv
Registering accessory 'homebridge-samsungtv.SamsungTV

---
*** WARNING *** The program node called DNSServiceRegister() which is not supported (or only supported partially) in the Apple Bonjour compatibility layer of Avahi.
*** WARNING *** Please fix your application to use the native API of Avahi!
*** WARNING *** For more information see <http://0pointer.de/avahi-compat?s=libdns_sd&e=node&f=DNSServiceRegister>
Loaded plugin: homebridge-yamaha
Registering accessory 'homebridge-yamaha.YamahaAVR
Registering platform 'homebridge-yamaha.YamahaAVR'

---
Loaded config.json with 4 accessories and 4 platforms.

---
Loading 4 platforms...
Initializing YamahaAVR platform...
Getting Yamaha AVR devices.
Initializing mcuiot platform...
/usr/local/lib/node_modules/homebridge/lib/api.js:106
      throw new Error("The requested platform '" + name + "' was not registered by any plugin.");
      ^

Error: The requested platform SmtpSensor was not registered by any plugin.
    at API.platform (/usr/local/lib/node_modules/homebridge/lib/api.js:106:13)
    at Server._loadPlatforms (/usr/local/lib/node_modules/homebridge/lib/server.js:263:45)
    at Server.run (/usr/local/lib/node_modules/homebridge/lib/server.js:71:36)
    at module.exports (/usr/local/lib/node_modules/homebridge/lib/cli.js:40:10)
    at Object.<anonymous> (/usr/local/lib/node_modules/homebridge/bin/homebridge:17:22)
    at Module._compile (module.js:413:34)
    at Object.Module._extensions..js (module.js:422:10)
    at Module.load (module.js:357:32)
    at Function.Module._load (module.js:314:12)
    at Function.Module.runMain (module.js:447:10)
```

how can I debug, find the problem?

here my config.json (config.json is validatet):

`{
        "platform": "SmtpSensor",
        "port": "2525",
        "sensors": [
            {
                "name": "Kamera Eingang",
                "keyword": "IP Camera 002-050-207"
            }
            ,
            {
                "name": "Kamera Kellertreppe",
                "keyword": "IP Camera 002-050-212"
            }
        ]
    },`

thx neo

**Comment by gilesmartin** [comment]
Seems the author may have gone silent but i found the solution. The plugin gets installed under the ~/.homebridge/node_modules directory instead of the /usr/local/lib/node_modules directory.

Performing "cp -r ~/.homebridge/node_modules/homebridge-smtpsensor /usr/local/lib/node_modules/" allows it to load and homebridge to complete startup.
